#!/bin/bash

commit_message_file=$1
commit_message=$(cat "$commit_message_file")
commit_regex="^((wip|Merge?.+)|(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|release)(\([-A-Za-z0-9_ ]+\))?!?: .+)"

if [[ ! $commit_message =~ $commit_regex ]]; then
	echo "Error: The commit message does not adhere to the expected format."
	echo "The commit message should have the format:"
	echo "<type>[optional scope]: <description>"
	exit 1
fi

exit 0
