#!/bin/bash

commit_message_file=$1
commit_message=$(cat "$commit_message_file")
commit_regex="^(wip|Merge?.+|Revert?.+)|(chore|docs|feat|fix|perf|refactor|style|test)(\([-A-Za-z0-9_ ]+\))?!?: .+"

if [[ ! $commit_message =~ $commit_regex ]]; then
	echo -e "\e[91mError: The commit message does not adhere to the expected format.\e[0m\n"
	echo -e "\e[94mThe commit message should have the format:\e[0m"
	echo -e "\e[93m<type>\e[0m[\e[96m<optional scope>\e[0m]: \e[97m<description>\e[0m\n"
	echo -e "\e[97m<body>\e[0m\n"
	echo -e "\e[97m<footer>\e[0m\n"
	exit 1
fi

exit 0
